import { Box, Flex, Text } from "@chakra-ui/react";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";

type SavedPageProps = {};

const SavedPage: React.FC<SavedPageProps> = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Saved Posts • Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Instagram_icon.png/2048px-Instagram_icon.png"
        />
      </Head>

      <Flex p={{ base: "0px 0px 16px 0px ", md: "30px 0px" }} justify="center">
        <Flex maxW="935px" w="100%">
          <Flex align="center" cursor="pointer" onClick={() => router.back()}>
            <svg
              aria-label="Back"
              color="#8e8e8e"
              fill="#8e8e8e"
              height="18"
              role="img"
              viewBox="0 0 24 24"
              width="18"
              className="rotateIcon"
            >
              <path d="M21 17.502a.997.997 0 01-.707-.293L12 8.913l-8.293 8.296a1 1 0 11-1.414-1.414l9-9.004a1.03 1.03 0 011.414 0l9 9.004A1 1 0 0121 17.502z"></path>
            </svg>
            <Text fontWeight={600} fontSize="11pt" color="#8e8e8e" ml={3}>
              Saved
            </Text>
          </Flex>
        </Flex>
      </Flex>
    </>
  );
};
export default SavedPage;
