import { Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { useAuthState } from "react-firebase-hooks/auth";
import HomeLeft from "../components/home/HomeLeft";
import HomeRight from "../components/home/HomeRight";
import PageContent from "../components/layout/PageContent";
import Posts from "../components/post/Posts";
import { auth } from "../firebase/clientApp";

const Home: NextPage = () => {
  const [user] = useAuthState(auth);

  return (
    <div>
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Instagram_icon.png/2048px-Instagram_icon.png"
        />
      </Head>

      <PageContent>
        <>
          <HomeLeft user={user} />
          <Posts />
        </>
        <>{user && <HomeRight />}</>
      </PageContent>
    </div>
  );
};

export default Home;
