import { Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import HomeLeft from "../components/home/HomeLeft";
import HomeRight from "../components/home/HomeRight";
import PageContent from "../components/layout/PageContent";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Instagram_icon.png/2048px-Instagram_icon.png"
        />
      </Head>

      <PageContent>
        <>
          <HomeLeft />
        </>
        <>
          <HomeRight />
        </>
      </PageContent>
    </div>
  );
};

export default Home;
