import {
  Avatar,
  Box,
  Flex,
  Image,
  InputGroup,
  InputRightAddon,
  Skeleton,
  Stack,
  Text,
  Textarea,
} from "@chakra-ui/react";
import { doc, getDoc } from "firebase/firestore";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import { Post } from "../../atoms/postsAtom";
import PostLoader from "../../components/loader/PostLoader";
import PostDetailItem from "../../components/post/PostDetailItem";
import { firestore } from "../../firebase/clientApp";
import usePosts from "../../hooks/usePosts";

type PostPageProps = {};

const PostPage: React.FC<PostPageProps> = () => {
  const [loading, setLoading] = useState(false);
  const { postStateValue, setPostStateValue, onDeletePost, likePost } =
    usePosts();
  const post = postStateValue.selectedPost;
  const router = useRouter();
  const { pid } = router.query;

  const fetchPost = async (postId: string) => {
    setLoading(true);
    try {
      const postDocRef = doc(firestore, "posts", postId);
      const postDoc = await getDoc(postDocRef);
      setPostStateValue((prev) => ({
        ...prev,
        selectedPost: { id: postDoc.id, ...postDoc.data() } as Post,
      }));
    } catch (error) {
      console.log("fetchPost Error", error);
    }
    setLoading(false);
  };

  useEffect(() => {
    if (pid && !postStateValue.selectedPost) {
      fetchPost(pid as string);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [pid, postStateValue.selectedPost]);

  return (
    <>
      <Head>
        <title>
          {post?.name} on Instagram: {`"${post?.caption}"`}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Instagram_icon.png/2048px-Instagram_icon.png"
        />
      </Head>

      <>
        {post && (
          <>
            <Flex
              justify="center"
              p={{ base: "0px 0px 16px 0px ", md: "30px 0px" }}
              display={{ base: "none", md: "flex" }}
            >
              <Flex
                flexDir={{ base: "column", md: "row" }}
                justify="center"
                w="100%"
                maxWidth="935px"
              >
                {loading && <Skeleton w="60%" h="350px" />}
                <Box
                  w={{ base: "100%", md: "60%" }}
                  display={loading ? "none" : "flex"}
                  justifyContent="center"
                  bg="black"
                >
                  <Image src={post.imageURL} alt="" objectFit="contain" />
                </Box>

                <Box w={{ base: "100%", md: "40%" }}>
                  <PostDetailItem
                    post={post}
                    onDeletePost={onDeletePost}
                    likePost={likePost}
                  />
                </Box>
              </Flex>
            </Flex>

            <Stack
              display={{ base: "unset", md: "none" }}
              position="absolute"
              top={0}
              w="100%"
              h="100%"
              zIndex={10000}
              bg="white"
            >
              <Flex
                align="center"
                justify="space-between"
                h="44px"
                p="0px 16px"
                borderBottom="1px solid"
                borderColor="gray.300"
              >
                <svg
                  aria-label="Back"
                  color="#262626"
                  fill="#262626"
                  height="24"
                  role="img"
                  viewBox="0 0 24 24"
                  width="24"
                  className="rotateIcon"
                  onClick={() => router.back()}
                >
                  <path d="M21 17.502a.997.997 0 01-.707-.293L12 8.913l-8.293 8.296a1 1 0 11-1.414-1.414l9-9.004a1.03 1.03 0 011.414 0l9 9.004A1 1 0 0121 17.502z"></path>
                </svg>
                <Text fontWeight={600}>Comments</Text>
                <svg
                  aria-label="Share Post"
                  color="#262626"
                  fill="#262626"
                  height="24"
                  role="img"
                  viewBox="0 0 24 24"
                  width="24"
                >
                  <line
                    fill="none"
                    stroke="currentColor"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    x1="22"
                    x2="9.218"
                    y1="3"
                    y2="10.083"
                  ></line>
                  <polygon
                    fill="none"
                    points="11.698 20.334 22 3.001 2 3.001 9.218 10.084 11.698 20.334"
                    stroke="currentColor"
                    strokeLinejoin="round"
                    strokeWidth="2"
                  ></polygon>
                </svg>
              </Flex>

              <Flex
                mt="0rem !important"
                padding="8px 16px"
                bg="#efefef"
                align="center"
              >
                <Avatar src={post.profileImg} size="sm" mr={3} />
                <InputGroup
                  border="1px solid"
                  borderRadius="full"
                  borderColor="gray.300"
                >
                  <Textarea
                    border="none"
                    borderRadius="full"
                    focusBorderColor="none"
                    placeholder="Add a comment..."
                    _placeholder={{ fontSize: "10pt" }}
                    fontSize="10pt"
                    minH="unset"
                    h="44px"
                    p="12px 16px"
                    resize="none"
                    bg="white"
                  />
                  <InputRightAddon
                    border="none"
                    bg="white"
                    borderRadius="full"
                    fontSize="11.5pt"
                    fontWeight={600}
                    color="brand.100"
                  >
                    Post
                  </InputRightAddon>
                </InputGroup>
              </Flex>
            </Stack>
          </>
        )}
      </>
    </>
  );
};
export default PostPage;
