import { Flex, Text } from "@chakra-ui/react";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";

const PageNotFound: React.FC = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Page not found • Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Instagram_icon.png/2048px-Instagram_icon.png"
        />
      </Head>

      <Flex flexDir="column" align="center" p="40px 30px">
        <Text
          fontWeight={700}
          fontSize="16pt"
        >{`Sorry, this page is'nt available`}</Text>

        <Text fontSize="11.5pt" mt={6}>
          The link you followed may be broken, or the page may have been
          removed.{" "}
          <span
            style={{ cursor: "pointer", color: "#0095f6" }}
            onClick={() => router.push("/")}
          >
            Go back to Instagram
          </span>
        </Text>
      </Flex>
    </>
  );
};
export default PageNotFound;
