import {
  Button,
  Divider,
  Flex,
  Image,
  Input,
  Stack,
  Text,
} from "@chakra-ui/react";
import { User } from "firebase/auth";
import { addDoc, collection, serverTimestamp } from "firebase/firestore";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import { useCreateUserWithEmailAndPassword } from "react-firebase-hooks/auth";
import OAuthButtons from "../../components/OAuthButtons";
import { auth, firestore } from "../../firebase/clientApp";
import { FIREBASE_ERRORS } from "../../firebase/errors";

const SignupPage = () => {
  const [signupForm, setSignupForm] = useState({
    email: "",
    password: "",
    fullname: "",
    username: "",
  });
  const [createUserWithEmailAndPassword, user, userLoading, userError] =
    useCreateUserWithEmailAndPassword(auth);
  const [loading, setLoading] = useState(false);
  const router = useRouter();

  const onChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setSignupForm((prev) => ({
      ...prev,
      [event.target.name]: event.target.value,
    }));
  };

  const userDisabled = !signupForm.email && !signupForm.password;

  const onSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    createUserWithEmailAndPassword(signupForm.email, signupForm.password);
  };

  // console.log(user);

  const createUserDocument = async (user: User) => {
    setLoading(true);
    try {
      await addDoc(collection(firestore, "users"), {
        uid: user.uid,
        fullname: signupForm.fullname,
        username: signupForm.username,
        email: user.email,
        follower: 0,
        following: 0,
        createdAt: serverTimestamp(),
      });
      router.push("/");
    } catch (error) {
      console.log("createUserDocument Error", error);
    }
    setLoading(false);
  };

  useEffect(() => {
    if (user) {
      createUserDocument(user.user);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [user]);

  return (
    <>
      <Head>
        <title>Signup • Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Instagram_icon.png/2048px-Instagram_icon.png"
        />
      </Head>

      <Flex justify="center">
        <Flex
          width={{ base: "100%", md: "350px" }}
          p="35px 0px"
          direction="column"
        >
          <Stack
            bg={{ base: "none", md: "white" }}
            width="100%"
            border={{ base: "none", md: "1px solid" }}
            borderColor={{ base: "none", md: "gray.200" }}
            p="0px 35px"
          >
            <Flex justify="center" width="100%">
              <Image
                src="https://www.instagram.com/static/images/web/logged_out_wordmark.png/7a252de00b20.png"
                alt=""
                maxH="100%"
                maxW="100%"
                p="36px 0px 10px 0px"
                objectFit="contain"
              />
            </Flex>

            <Text color="gray.500" textAlign="center" fontWeight={600} pb={3}>
              Sign up to see photos and videos from your friends.
            </Text>

            <OAuthButtons />

            <Flex align="center" p="10px 0px">
              <Divider />
              <Text
                p="0px 20px"
                fontWeight={600}
                color="gray.500"
                fontSize="11pt"
              >
                OR
              </Text>
              <Divider />
            </Flex>

            <Stack width="100%" justify="center">
              <form onSubmit={onSubmit}>
                <Stack pb={5}>
                  <Input
                    bg="rgb(250, 250, 250)"
                    borderRadius="3px"
                    placeholder="Mobile Number or Email"
                    fontSize="10pt"
                    _placeholder={{ fontSize: "9pt" }}
                    _focus={{
                      outline: "none",
                      border: "1px solid black",
                    }}
                    focusBorderColor="none"
                    required
                    type="email"
                    name="email"
                    onChange={onChange}
                  />
                  <Input
                    bg="rgb(250, 250, 250)"
                    borderRadius="3px"
                    placeholder="Full Name"
                    fontSize="10pt"
                    _placeholder={{ fontSize: "9pt" }}
                    _focus={{
                      outline: "none",
                      border: "1px solid black",
                    }}
                    focusBorderColor="none"
                    required
                    type="text"
                    name="fullname"
                    onChange={onChange}
                  />
                  <Input
                    bg="rgb(250, 250, 250)"
                    borderRadius="3px"
                    placeholder="Username"
                    fontSize="10pt"
                    _placeholder={{ fontSize: "9pt" }}
                    _focus={{
                      outline: "none",
                      border: "1px solid black",
                    }}
                    focusBorderColor="none"
                    required
                    type="text"
                    name="username"
                    onChange={onChange}
                  />
                  <Input
                    bg="rgb(250, 250, 250)"
                    borderRadius="3px"
                    placeholder="Password"
                    fontSize="10pt"
                    _placeholder={{ fontSize: "9pt" }}
                    _focus={{
                      outline: "none",
                      border: "1px solid black",
                    }}
                    focusBorderColor="none"
                    required
                    type="password"
                    name="password"
                    onChange={onChange}
                  />

                  <Text textAlign="center" color="red" fontSize="10pt">
                    {
                      FIREBASE_ERRORS[
                        userError?.message as keyof typeof FIREBASE_ERRORS
                      ]
                    }
                  </Text>

                  <Text textAlign="center" fontSize="9pt" pt={2}>
                    People who use our service may have uploaded your contact
                    information to Instagram. Learn More
                  </Text>
                  <Text textAlign="center" fontSize="9pt" pb={2}>
                    By signing up, you agree to our Terms , Privacy Policy and
                    Cookies Policy.
                  </Text>

                  <Button
                    height="30px"
                    type="submit"
                    isLoading={loading}
                    isDisabled={userDisabled}
                  >
                    Sign up
                  </Button>
                </Stack>
              </form>
            </Stack>
          </Stack>

          <Flex
            mt={2}
            bg={{ base: "none", md: "white" }}
            width="100%"
            border="1px solid"
            borderColor="gray.200"
            justify="center"
            p="20px 0px"
          >
            <Text
              align="center"
              fontSize="11pt"
              mr={1}
            >{`Don't have an account?`}</Text>
            <Link href="/login">
              <Text
                align="center"
                fontSize="11pt"
                color="brand.100"
                fontWeight={600}
                cursor="pointer"
              >
                Log In
              </Text>
            </Link>
          </Flex>

          <Stack justify="center" p="20px 0px">
            <Text textAlign="center" fontSize="11pt">
              Get the app.
            </Text>
            <Flex justify="center" pt={2}>
              <Image
                src="https://iconape.com/wp-content/png_logo_vector/download-on-the-app-store-flat-badge-logo.png"
                alt=""
                w="136px"
                mr={2}
              />
              <Image
                src="https://iconape.com/wp-content/png_logo_vector/get-it-on-google-play-2016-logo.png"
                alt=""
                w="136px"
              />
            </Flex>
          </Stack>
        </Flex>
      </Flex>
    </>
  );
};
export default SignupPage;
