import { Flex, Stack, Text } from "@chakra-ui/react";
import moment from "moment";
import Head from "next/head";
import React from "react";
import useUserData from "../../hooks/useUserData";

type ProfilePageProps = {};

const ProfilePage: React.FC<ProfilePageProps> = () => {
  const { userStateValue } = useUserData();
  const userData = userStateValue?.userData;

  // console.log(userData);

  return (
    <>
      <Head>
        <title>
          {userData?.fullname} {`(@${userData?.username})`} • Instagram
        </title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Instagram_icon.png/2048px-Instagram_icon.png"
        />
      </Head>

      <Stack h="calc(100vh - 60px)" align="center" justify="center">
        <Flex>
          <Text fontWeight={600} mr={1}>
            UID:
          </Text>
          <Text>{userData?.uid}</Text>
        </Flex>

        <Flex>
          <Text fontWeight={600} mr={1}>
            Full Name:
          </Text>
          <Text>{userData?.fullname}</Text>
        </Flex>
        <Flex>
          <Text fontWeight={600} mr={1}>
            Username:
          </Text>
          <Text>{userData?.username}</Text>
        </Flex>
        <Flex>
          <Text fontWeight={600} mr={1}>
            Email:
          </Text>
          <Text>{userData?.email}</Text>
        </Flex>
        {userData?.createdAt && (
          <Flex>
            <Text fontWeight={600} mr={1}>
              CreatedAt:
            </Text>
            <Text>
              {moment(new Date(userData.createdAt?.seconds * 1000)).fromNow()}
            </Text>
          </Flex>
        )}
      </Stack>
    </>
  );
};
export default ProfilePage;
